apiVersion: v1
kind: Pod
metadata:
  name: probe-and-publish
spec:
  containers:
    - name: probe-and-publish
      image: mamachanko/website-monitor:latest
      imagePullPolicy: Always
      command: [ "bash" ]
      args:
        - -c
        - |
          while true; do
            python -m website_monitor.probe_and_publish
            sleep 10
          done
      env:
        - name: WM_URL
          valueFrom:
            secretKeyRef:
              name: website-monitor-config
              key: wm.url
        - name: WM_STREAM_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: website-monitor-config
              key: wm.stream.bootstrap-servers
        - name: WM_STREAM_TOPIC
          valueFrom:
            secretKeyRef:
              name: website-monitor-config
              key: wm.stream.topic
        - name: WM_STREAM_SSL_CA_FILE
          value: "/var/secrets/wm.stream.ssl_ca_file"
        - name: WM_STREAM_SSL_CERT_FILE
          value: "/var/secrets/wm.stream.ssl_cert_file"
        - name: WM_STREAM_SSL_KEY_FILE
          value: "/var/secrets/wm.stream.ssl_key_file"
      volumeMounts:
        - mountPath: "/var/secrets"
          name: secrets-volume
          readOnly: true
  volumes:
    - name: secrets-volume
      secret:
        secretName: website-monitor-config
